cmake_minimum_required(VERSION 3.16)

if(NOT DEFINED INPUT)
  message(FATAL_ERROR "gen_wifi_secrets.cmake: missing -DINPUT=...")
endif()
if(NOT DEFINED OUTPUT)
  message(FATAL_ERROR "gen_wifi_secrets.cmake: missing -DOUTPUT=...")
endif()

set(_ssid "")
set(_pass "")

if(EXISTS "${INPUT}")
  file(READ "${INPUT}" _env_raw)
  string(REPLACE "\r\n" "\n" _env_raw "${_env_raw}")
  string(REPLACE "\r" "\n" _env_raw "${_env_raw}")
  string(REPLACE "\n" ";" _env_lines "${_env_raw}")

  foreach(_line IN LISTS _env_lines)
    string(STRIP "${_line}" _line)
    if(_line STREQUAL "")
      continue()
    endif()
    if(_line MATCHES "^[#;]")
      continue()
    endif()

    if(_line MATCHES "^(ssid|SSID)=(.*)$")
      set(_ssid "${CMAKE_MATCH_2}")
      string(STRIP "${_ssid}" _ssid)
      if(_ssid MATCHES "^\"(.*)\"$")
        set(_ssid "${CMAKE_MATCH_1}")
      endif()
    elseif(_line MATCHES "^(pass|PASS|password|PASSWORD)=(.*)$")
      set(_pass "${CMAKE_MATCH_2}")
      string(STRIP "${_pass}" _pass)
      if(_pass MATCHES "^\"(.*)\"$")
        set(_pass "${CMAKE_MATCH_1}")
      endif()
    endif()
  endforeach()
endif()

function(_escape_c_string out_var in_str)
  set(_s "${in_str}")
  string(REPLACE "\\" "\\\\" _s "${_s}")
  string(REPLACE "\"" "\\\"" _s "${_s}")
  string(REPLACE "\n" "\\n" _s "${_s}")
  set(${out_var} "${_s}" PARENT_SCOPE)
endfunction()

_escape_c_string(_ssid_esc "${_ssid}")
_escape_c_string(_pass_esc "${_pass}")

get_filename_component(_out_dir "${OUTPUT}" DIRECTORY)
file(MAKE_DIRECTORY "${_out_dir}")

file(WRITE "${OUTPUT}" "/* Auto-generated. Do not commit. */\n")
file(APPEND "${OUTPUT}" "#pragma once\n")
file(APPEND "${OUTPUT}" "#define TAB5_ENV_WIFI_SSID \"${_ssid_esc}\"\n")
file(APPEND "${OUTPUT}" "#define TAB5_ENV_WIFI_PASS \"${_pass_esc}\"\n")

