cmake_minimum_required(VERSION 3.16)

if(NOT DEFINED INPUT)
  message(FATAL_ERROR "gen_wifi_secrets.cmake: missing -DINPUT=...")
endif()
if(NOT DEFINED OUTPUT)
  message(FATAL_ERROR "gen_wifi_secrets.cmake: missing -DOUTPUT=...")
endif()

set(_ssid "")
set(_pass "")
set(_bailian_api_key "")
set(_bailian_matched FALSE)
set(_e2e_autorun "0")

if(EXISTS "${INPUT}")
  file(READ "${INPUT}" _env_raw)
  string(REPLACE "\r\n" "\n" _env_raw "${_env_raw}")
  string(REPLACE "\r" "\n" _env_raw "${_env_raw}")
  string(REPLACE "\n" ";" _env_lines "${_env_raw}")

  foreach(_line IN LISTS _env_lines)
    string(STRIP "${_line}" _line)
    # Strip any leading non-identifier chars (e.g. UTF-8 BOM pasted by Windows editors)
    string(REGEX REPLACE "^[^A-Za-z0-9_#;]+" "" _line "${_line}")
    if(DEFINED DEBUG AND DEBUG STREQUAL "1")
      if(_line MATCHES "BAILIAN_API_KEY")
        set(_safe_line "${_line}")
        string(REGEX REPLACE "=.*$" "=***" _safe_line "${_safe_line}")
        message(STATUS "gen_wifi_secrets: saw line: ${_safe_line}")
      endif()
    endif()
    if(_line STREQUAL "")
      continue()
    endif()
    if(_line MATCHES "^[#;]")
      continue()
    endif()

    if(_line MATCHES "^[ \t]*(ssid|SSID)[ \t]*=[ \t]*(.*)$")
      set(_ssid "${CMAKE_MATCH_2}")
      string(STRIP "${_ssid}" _ssid)
      if(_ssid MATCHES "^\"(.*)\"$")
        set(_ssid "${CMAKE_MATCH_1}")
      endif()
    elseif(_line MATCHES "^[ \t]*(pass|PASS|password|PASSWORD)[ \t]*=[ \t]*(.*)$")
      set(_pass "${CMAKE_MATCH_2}")
      string(STRIP "${_pass}" _pass)
      if(_pass MATCHES "^\"(.*)\"$")
        set(_pass "${CMAKE_MATCH_1}")
      endif()
    elseif(_line MATCHES "^[ \t]*(BAILIAN_API_KEY|bailian_api_key|DASHSCOPE_API_KEY|dashscope_api_key)[ \t]*=[ \t]*(.*)$")
      set(_bailian_api_key "${CMAKE_MATCH_2}")
      set(_bailian_matched TRUE)
      string(STRIP "${_bailian_api_key}" _bailian_api_key)
      if(_bailian_api_key MATCHES "^\"(.*)\"$")
        set(_bailian_api_key "${CMAKE_MATCH_1}")
      endif()
    elseif(_line MATCHES "^[ \t]*(E2E_AUTORUN|e2e_autorun)[ \t]*=[ \t]*(.*)$")
      set(_e2e_autorun "${CMAKE_MATCH_2}")
      string(STRIP "${_e2e_autorun}" _e2e_autorun)
      if(_e2e_autorun MATCHES "^\"(.*)\"$")
        set(_e2e_autorun "${CMAKE_MATCH_1}")
      endif()
    endif()
  endforeach()
endif()

function(_escape_c_string out_var in_str)
  set(_s "${in_str}")
  string(REPLACE "\\" "\\\\" _s "${_s}")
  string(REPLACE "\"" "\\\"" _s "${_s}")
  string(REPLACE "\n" "\\n" _s "${_s}")
  set(${out_var} "${_s}" PARENT_SCOPE)
endfunction()

_escape_c_string(_ssid_esc "${_ssid}")
_escape_c_string(_pass_esc "${_pass}")
_escape_c_string(_bailian_api_key_esc "${_bailian_api_key}")
string(TOLOWER "${_e2e_autorun}" _e2e_autorun_lc)
set(_e2e_autorun_num 0)
if(_e2e_autorun_lc STREQUAL "1" OR _e2e_autorun_lc STREQUAL "true" OR _e2e_autorun_lc STREQUAL "yes" OR _e2e_autorun_lc STREQUAL "on")
  set(_e2e_autorun_num 1)
endif()

if(DEFINED DEBUG AND DEBUG STREQUAL "1")
  string(LENGTH "${_bailian_api_key}" _bk_len)
  message(STATUS "gen_wifi_secrets: bailian_matched=${_bailian_matched} bailian_len=${_bk_len}")
endif()

get_filename_component(_out_dir "${OUTPUT}" DIRECTORY)
file(MAKE_DIRECTORY "${_out_dir}")

file(WRITE "${OUTPUT}" "/* Auto-generated. Do not commit. */\n")
file(APPEND "${OUTPUT}" "#pragma once\n")
file(APPEND "${OUTPUT}" "#define TAB5_ENV_WIFI_SSID \"${_ssid_esc}\"\n")
file(APPEND "${OUTPUT}" "#define TAB5_ENV_WIFI_PASS \"${_pass_esc}\"\n")
file(APPEND "${OUTPUT}" "#define TAB5_ENV_BAILIAN_API_KEY \"${_bailian_api_key_esc}\"\n")
file(APPEND "${OUTPUT}" "#define TAB5_ENV_E2E_AUTORUN ${_e2e_autorun_num}\n")
